{"name": "test_add_numbers", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3\n +  where 2 = add_two_numbers(1, 1)", "trace": "def test_add_numbers():\n>       assert add_two_numbers(1, 1) == 3\nE       assert 2 == 3\nE        +  where 2 = add_two_numbers(1, 1)\n\nmain.py:18: AssertionError"}, "start": 1717525052150, "stop": 1717525052150, "uuid": "50909f81-8851-475a-aa12-27b8587f9c87", "historyId": "f8a7459063b7be16c8b4229a3069e5fc", "testCaseId": "f8a7459063b7be16c8b4229a3069e5fc", "fullName": "main#test_add_numbers", "labels": [{"name": "suite", "value": "main"}, {"name": "host", "value": "DJSTATION_NEW"}, {"name": "thread", "value": "27516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}