{"name": "test_add_negative_numbers", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2\n +  where 3 = add_two_numbers(1, 2)", "trace": "prepare_data = (1, 2)\n\n    def test_add_negative_numbers(prepare_data):\n>       assert add_two_numbers(prepare_data[0], prepare_data[1]) == 2\nE       assert 3 == 2\nE        +  where 3 = add_two_numbers(1, 2)\n\nmain.py:27: AssertionError"}, "start": 1717524018821, "stop": 1717524018822, "uuid": "071e1a2e-4942-4034-a8c5-1585631dfd4d", "historyId": "82e2305ee4f75679d39e8de2b77e5283", "testCaseId": "82e2305ee4f75679d39e8de2b77e5283", "fullName": "main#test_add_negative_numbers", "labels": [{"name": "suite", "value": "main"}, {"name": "host", "value": "DJSTATION_NEW"}, {"name": "thread", "value": "11244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}