{"name": "My New tests", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2\n +  where 3 = add_two_numbers(1, 2)", "trace": "prepare_data = (1, 2)\n\n    @allure.title(\"My New tests\")\n    def test_add_negative_numbers(prepare_data):\n>       assert add_two_numbers(prepare_data[0], prepare_data[1]) == 2\nE       assert 3 == 2\nE        +  where 3 = add_two_numbers(1, 2)\n\nmain.py:29: AssertionError"}, "start": 1717524952300, "stop": 1717524952301, "uuid": "66af95b9-9cf5-4b50-849f-0126a9ad1926", "historyId": "82e2305ee4f75679d39e8de2b77e5283", "testCaseId": "82e2305ee4f75679d39e8de2b77e5283", "fullName": "main#test_add_negative_numbers", "labels": [{"name": "suite", "value": "main"}, {"name": "host", "value": "DJSTATION_NEW"}, {"name": "thread", "value": "24248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}